server:
  port: "${SERVER_PORT:8080}"

spring:
##  数据源配置
  datasource:
    url: "jdbc:postgresql://122.51.45.249:5432/laa" #k8s env
    username: "${NAME:postgres}"
    password: "${PASSWORD:h3c.com!}"
    driverClassName: "org.postgresql.Driver"
##  邮件配置
  mail:
    host: "smtp.qq.com"
    port: 465
    username: "1067418318@qq.com"
    password: "kyamfeexmnarbejc"

# IM端口
laa:
  im:
    port: "${IM_PORT:9432}"