server:
  port: "${SERVER_PORT:8080}"

##  数据源配置
spring:
  datasource:
    url: "jdbc:mysql://106.14.169.164:3306/game"
    username: "${USERNAME:root}"
    password: "${PASSWORD:12345678}"
    driver-class-name: "com.mysql.jdbc.Driver"

# IM端口
laa:
  im:
    port: "${IM_PORT:9432}"