server:
  port: "${SERVER_PORT:8080}"

##  数据源配置
spring:
  datasource:
    url: "jdbc:mysql://111.231.64.142:3306/laa"
    username: "${NAME:root}"
    password: "${PASSWORD:xy520tgp}"
    driver-class-name: "com.mysql.jdbc.Driver"

# IM端口
laa:
  im:
    port: "${IM_PORT:9432}"