server:
  port: "${SERVER_PORT:8080}"

##  数据源配置
spring:
  datasource:
    url: "jdbc:mysql://106.14.169.164:3306/game"
    username: "root"
    password: "xy520tgp"
    driver-class-name: "com.mysql.jdbc.Driver"

